extends: ['airbnb-base', 'plugin:prettier/recommended']
plugins: ['import', 'prettier']
rules:
  'class-methods-use-this': 0
  'no-console': 0
  'no-underscore-dangle': 0
  'no-use-before-define': ['error', { 'functions': false, 'classes': true }]
  'prefer-destructuring': 0
  'strict': 0
env:
  mocha: true
